# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootballApp' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootballApp

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
