# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'UIImageColors'
end

target 'FootballApp' do
  use_frameworks!
  shared_pods
end

target 'FootballAppTests' do
  use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

